shell = "zsh"

[templates]
defer = """
{{ hooks?.pre | nl }}
{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
"""

fzf-install = """
{{ hooks?.pre | nl }}
{{ dir }}/install --bin > /dev/null
path=($path {{ dir }}/bin(N-/))
{{ hooks?.post | nl }}
"""

fzf-source = "source <(fzf --zsh)"

#
# Deferred Loading of Plugins in Zsh
#

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

#
# Zsh Initialization
#

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

#
# Zsh-related Plugins
#

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['defer']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.zsh-autopair]
github = 'hlissner/zsh-autopair'
apply = ['defer']

[plugins.zsh-history-on-success]
github = 'nyoungstudios/zsh-history-on-success'

# コマンド入力途中で上下キー押したときの過去履歴がいい感じに出るようになる
[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'
apply = ['defer']

# 256色表示にする
[plugins.zsh-256color]
github = 'chrissicool/zsh-256color'

# jq をインタラクティブに使える。JSONを標準出力に出すコマンドを入力した状態で `Alt+j` すると jq のクエリが書ける。
# 要 jq
[plugins.zsh-jq]
github = 'reegnz/jq-zsh-plugin'
apply = ['defer']

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
use = [
	#
	# Load necessary functions first
	#
	'lib/functions.zsh',
	#
	# Load other useful libraries
	#
	'lib/completion.zsh',
	'lib/history.zsh',
	'lib/termsupport.zsh',
	#
	# Load some plugins
	#
	'plugins/fzf/fzf.plugin.zsh',
]

[plugins.zsh-history-shell-options]
inline = '''
setopt INC_APPEND_HISTORY_TIME
setopt INC_APPEND_HISTORY
'''

#
# Mise for managing multiple versions of tools
#

[plugins.mise]
inline = 'eval "$(~/.local/bin/mise activate zsh)"'

#
# Language-related plugins
#

[plugins.lang]
inline = '''
function _lang() {
    export LANG='en_US.UTF-8'
}
zsh-defer _lang
'''

[plugins.editor-vim]
inline = '''
function _editor() {
    export EDITOR='vim'
}
zsh-defer _editor
'''

[plugins.theme-dracula]
github = 'dracula/zsh'
apply = ['defer']

[plugins.gha-fzf]
inline = '''
# ghqでgetしたレポジトリ一覧をfzfで絞り込み素早くcdする
# レポジトリのTOPにあるREADMEをbatでpreviewする機能付き
# https://qiita.com/kompiro/items/a09c0b44e7c741724c80
function cd-fzf-ghqlist() {
    local GHQ_ROOT=`ghq root`
    local REPO=`ghq list -p | sed -e 's;'${GHQ_ROOT}/';;g' |fzf --height 70% --preview "bat --color=always --style=header,grid --line-range :80 $(ghq root)/{}/README.*" +m`
    if [ -n "${REPO}" ]; then
        BUFFER="cd ${GHQ_ROOT}/${REPO}"
    fi
    zle accept-line
}
zle -N cd-fzf-ghqlist
bindkey '^G' cd-fzf-ghqlist
'''

[plugins.bat]
inline = '[[ $(command -v bat) ]] && alias cat=bat'

[plugins.eza]
inline = '''
# ezaがインストールされてたらlsの代わりに使うようにする
if [[ $(command -v eza) ]]; then
    alias e='eza --icons --git'
    alias l=e
    alias ls=e
    alias ea='eza -a --icons --git'
    alias la=ea
    alias ee='eza -aahl --icons --git'
    alias ll=ee
    alias et='eza -T -L 3 -a -I "node_modules|.git|.cache" --icons'
    alias lt=et
    alias eta='eza -T -a -I "node_modules|.git|.cache" --color=always --icons | less -r'
    alias lta=eta
    alias l='clear && ls'
fi
'''

[plugins.history-fzf]
inline = '''
# historyをfzfで絞り込む
function buffer-fzf-history() {
    local HISTORY=$(history -n -r 1 | fzf +m)
    BUFFER=$HISTORY
    if [ -n "$HISTORY" ]; then
        CURSOR=$#BUFFER
    else
        zle accept-line
    fi
}
zle -N buffer-fzf-history
bindkey '^R' buffer-fzf-history
'''

[plugins.cd-fzf]
inline = '''
# ディレクトリ配下のディレクトリに移動する(find > cd)
# https://qiita.com/lighttiger2505/items/1d2b93cbbfb31fa87786
cd-fzf-find() {
    local DIR=$(find ./ -path '*/\.*' -name .git -prune -o -type d -print 2> /dev/null | fzf +m)
    if [ -n "$DIR" ]; then
        cd $DIR
    fi
}
alias fd=cd-fzf-find
'''

[plugins.rbenv]
inline = '[[ $(command -v rbenv) ]] && eval "$(rbenv init - zsh)"'

[plugins.direnv]
inline = '[[ $(command -v direnv) ]] && eval "$(direnv hook zsh)"'

#
# Zoxide (smarter cd)
#

[plugins.zoxide]
inline = '[[ $(command -v zoxide) ]] && eval "$(zoxide init zsh)"'

#
# Prompt
#

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
