shell = "zsh"

[templates]
defer = """
{{ hooks?.pre | nl }}
{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
"""

#
# Deferred Loading of Plugins in Zsh
#

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

#
# Zsh Initialization
#

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

#
# Zsh-related Plugins
#

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['defer']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

#
# Mise for managing multiple versions of tools
#

[plugins.mise]
inline = 'eval "$(~/.local/bin/mise activate zsh)"'
