Host *
  IdentityAgent ~/.1password/agent.sock
  IdentitiesOnly yes
  AddKeysToAgent no
  ControlMaster auto
  ControlPath ~/.ssh/conf.d/cm/mux-%C.sock
  ControlPersist 30m
  ServerAliveInterval 60
  ServerAliveCountMax 3
