[tools]
ghq = "1.10.1"
"github:suzuki-shunsuke/ghalint" = "1.5.5"
"github:suzuki-shunsuke/pinact" = "3.9.0"
"github:rtk-ai/rtk" = "v0.37.2"
"github:Warashi/cage" = "0.1.13"
"github:azu/dockerfile-pin" = "1.2.2"
rust = "1.95.0"
