name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run shellcheck
        uses: reviewdog/action-shellcheck@d0b8d5fd7fad6afdb6e1b6ce1778892be4d1f427 # v1.34.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          pattern: "*.sh"
          exclude: "./.git/*"
